services:
  web:
    image: guzmanbenjamin/webmock:v1.0-alpha
    restart: on-failure
    ports:
      - "80:3000" # comment if deploying v1 and v2 on same host
    volumes:
      - ".env.prod:/usr/src/.env"
    links:
      - "v1-db:postgres"
    networks:
      webmock-net:
        aliases:
          - v1
       internal-net:
          

  db:
    image: postgres
    restart: on-failure
    volumes:
      - "./db/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh"
    environment:
      - "POSTGRES_PASSWORD=pass"
    networks:
      - internal-net

networks:
  webmock-net:
    external: true
  internal-net:
    driver: bridge
    internal: true
