services:
  # microservices don't need to export ports
  # since all connections from gateway
  # are done inside docker's network
  auth:
    image: guzmanbenjamin/webmock-auth:v2.0-alpha
    restart: on-failure
    #ports:
    #  - "127.0.0.1:9000:9000"
    volumes:
      - "./backend/auth/.env.prod:/.env"
      - "./backend/auth/secret.txt:/secret.txt"

  cart:
    image: guzmanbenjamin/webmock-cart:v2.0-alpha
    restart: on-failure
    #ports:
    #  - "127.0.0.1:3000:3000"
    volumes:
      - "./backend/cart/.env.prod:/usr/src/.env"
    links:
      - "postgres:postgres"
      - "mongo:mongo"
      - "auth:auth"

  content:
    image: guzmanbenjamin/webmock-content:v2.0-alpha
    restart: on-failure
    #ports:
    #  - "127.0.0.1:5000:3000"
    volumes:
      - "./backend/content/.env.prod:/usr/src/.env"
    links:
      - "postgres:postgres"
      - "auth:auth"

  users:
    image: guzmanbenjamin/webmock-users:v2.0-alpha
    restart: on-failure
    #ports:
    #  - "127.0.0.1:4000:3000"
    volumes:
      - "./backend/users/.env.prod:/usr/src/.env"
    links:
      - "postgres:postgres"
      - "auth:auth"

  postgres:
    image: postgres
    restart: on-failure
    volumes:
      - "./postgres/001-db-init.sh:/docker-entrypoint-initdb.d/001-db-init.sh"
      - "./postgres/002-ddl.sql:/docker-entrypoint-initdb.d/002-ddl.sql"
    environment:
      - "POSTGRES_PASSWORD=pass"

  mongo:
    image: mongo
    restart: on-failure
    volumes:
      - "./mongo/001-users.js:/docker-entrypoint-initdb.d/001-users.js"
    command: --auth

  gateway:
    image: guzmanbenjamin/webmock-gateway:v2.0-alpha
    restart: on-failure
    ports:
      - "80:80"
    environment:
      - "GATEWAY_BASE_URL=https://test.benjaminguzman.dev"
      #- "GATEWAY_BASE_URL=http://127.0.0.1" # for local deployment
    links:
      - "cart:cart"
      - "users:users"
      - "content:content"
