services:
  mongo:
    image: mongo
    restart: on-failure
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - "./mongo/001-users.js:/docker-entrypoint-initdb.d/001-users.js"
    command: --auth
