services:
  web:
    image: guzmanbenjamin/webmock:v1.0-alpha
    restart: on-failure
    ports:
      - "80:3000"
    volumes:
      - ".env.prod:/usr/src/.env"
    links:
      - "db:postgres"

  db:
    image: postgres
    restart: on-failure
    volumes:
      - "./db/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh"
    environment:
      - "POSTGRES_PASSWORD=pass"
