// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: protobuf/auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecodeStatus int32

const (
	DecodeStatus_VALID   DecodeStatus = 0
	DecodeStatus_EXPIRED DecodeStatus = 1
	DecodeStatus_INVALID DecodeStatus = 2
)

// Enum value maps for DecodeStatus.
var (
	DecodeStatus_name = map[int32]string{
		0: "VALID",
		1: "EXPIRED",
		2: "INVALID",
	}
	DecodeStatus_value = map[string]int32{
		"VALID":   0,
		"EXPIRED": 1,
		"INVALID": 2,
	}
)

func (x DecodeStatus) Enum() *DecodeStatus {
	p := new(DecodeStatus)
	*p = x
	return p
}

func (x DecodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DecodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_auth_proto_enumTypes[0].Descriptor()
}

func (DecodeStatus) Type() protoreflect.EnumType {
	return &file_protobuf_auth_proto_enumTypes[0]
}

func (x DecodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DecodeStatus.Descriptor instead.
func (DecodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_auth_proto_rawDescGZIP(), []int{0}
}

type UserId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *UserId) Reset() {
	*x = UserId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserId) ProtoMessage() {}

func (x *UserId) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserId.ProtoReflect.Descriptor instead.
func (*UserId) Descriptor() ([]byte, []int) {
	return file_protobuf_auth_proto_rawDescGZIP(), []int{0}
}

func (x *UserId) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type JWT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jwt string `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
}

func (x *JWT) Reset() {
	*x = JWT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JWT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWT) ProtoMessage() {}

func (x *JWT) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWT.ProtoReflect.Descriptor instead.
func (*JWT) Descriptor() ([]byte, []int) {
	return file_protobuf_auth_proto_rawDescGZIP(), []int{1}
}

func (x *JWT) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

type DecodedJWT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status DecodeStatus `protobuf:"varint,1,opt,name=status,proto3,enum=auth.DecodeStatus" json:"status,omitempty"`
	UserId string       `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *DecodedJWT) Reset() {
	*x = DecodedJWT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecodedJWT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodedJWT) ProtoMessage() {}

func (x *DecodedJWT) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodedJWT.ProtoReflect.Descriptor instead.
func (*DecodedJWT) Descriptor() ([]byte, []int) {
	return file_protobuf_auth_proto_rawDescGZIP(), []int{2}
}

func (x *DecodedJWT) GetStatus() DecodeStatus {
	if x != nil {
		return x.Status
	}
	return DecodeStatus_VALID
}

func (x *DecodedJWT) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_protobuf_auth_proto protoreflect.FileDescriptor

var file_protobuf_auth_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x75, 0x74, 0x68, 0x22, 0x20, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x17, 0x0a,
	0x03, 0x4a, 0x57, 0x54, 0x12, 0x10, 0x0a, 0x03, 0x6a, 0x77, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6a, 0x77, 0x74, 0x22, 0x50, 0x0a, 0x0a, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65,
	0x64, 0x4a, 0x57, 0x54, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x44, 0x65, 0x63, 0x6f,
	0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x2a, 0x33, 0x0a, 0x0c, 0x44, 0x65, 0x63, 0x6f,
	0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x41, 0x4c, 0x49,
	0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x01,
	0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x02, 0x32, 0x5a, 0x0a,
	0x04, 0x41, 0x75, 0x74, 0x68, 0x12, 0x26, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a,
	0x57, 0x54, 0x12, 0x0c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x1a, 0x09, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4a, 0x57, 0x54, 0x22, 0x00, 0x12, 0x2a, 0x0a,
	0x09, 0x64, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x4a, 0x57, 0x54, 0x12, 0x09, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x4a, 0x57, 0x54, 0x1a, 0x10, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x44, 0x65, 0x63,
	0x6f, 0x64, 0x65, 0x64, 0x4a, 0x57, 0x54, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x61,
	0x75, 0x74, 0x68, 0x3b, 0x61, 0x75, 0x74, 0x68, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protobuf_auth_proto_rawDescOnce sync.Once
	file_protobuf_auth_proto_rawDescData = file_protobuf_auth_proto_rawDesc
)

func file_protobuf_auth_proto_rawDescGZIP() []byte {
	file_protobuf_auth_proto_rawDescOnce.Do(func() {
		file_protobuf_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_auth_proto_rawDescData)
	})
	return file_protobuf_auth_proto_rawDescData
}

var file_protobuf_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_auth_proto_goTypes = []interface{}{
	(DecodeStatus)(0),  // 0: auth.DecodeStatus
	(*UserId)(nil),     // 1: auth.UserId
	(*JWT)(nil),        // 2: auth.JWT
	(*DecodedJWT)(nil), // 3: auth.DecodedJWT
}
var file_protobuf_auth_proto_depIdxs = []int32{
	0, // 0: auth.DecodedJWT.status:type_name -> auth.DecodeStatus
	1, // 1: auth.Auth.createJWT:input_type -> auth.UserId
	2, // 2: auth.Auth.decodeJWT:input_type -> auth.JWT
	2, // 3: auth.Auth.createJWT:output_type -> auth.JWT
	3, // 4: auth.Auth.decodeJWT:output_type -> auth.DecodedJWT
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_auth_proto_init() }
func file_protobuf_auth_proto_init() {
	if File_protobuf_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JWT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecodedJWT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_auth_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_auth_proto_goTypes,
		DependencyIndexes: file_protobuf_auth_proto_depIdxs,
		EnumInfos:         file_protobuf_auth_proto_enumTypes,
		MessageInfos:      file_protobuf_auth_proto_msgTypes,
	}.Build()
	File_protobuf_auth_proto = out.File
	file_protobuf_auth_proto_rawDesc = nil
	file_protobuf_auth_proto_goTypes = nil
	file_protobuf_auth_proto_depIdxs = nil
}
